const Koa = require('koa')
const app = new Koa()
const respDurationMiddleware =  require('./components/koa_response_duration')
app.use(respDurationMiddleware)
const respHeaderMiddleware = require('./components/koa_response_header')
app.use(respHeaderMiddleware)
const respDataMiddleware = require('./components/koa_response_data')
app.use(respDataMiddleware)
app.listen(8888)
